"""empty message

Revision ID: 7d99a90e2a25
Revises: 
Create Date: 2021-01-04 14:19:52.290772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d99a90e2a25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enzyme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('catalogue_number', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enzyme_catalogue_number'), 'enzyme', ['catalogue_number'], unique=True)
    op.create_index(op.f('ix_enzyme_name'), 'enzyme', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enzyme_name'), table_name='enzyme')
    op.drop_index(op.f('ix_enzyme_catalogue_number'), table_name='enzyme')
    op.drop_table('enzyme')
    # ### end Alembic commands ###
